backend:
  name: github
  repo: RadioParalelo/indymedia-pt-hugo # Replace with your GitHub username and repo name
  branch: main # Your repository's default branch

media_folder: "static/images"
public_folder: "images"

collections:
  - name: "posts" # Collection name
    label: "Posts"
    folder: "content/posts" # Where your Hugo posts are stored
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }

